export class Poliza {
    public ID: number;
    public id_cliente: number;
    public nombre_cliente: string;
    public descripcion: string;
    public id_aseguradora: number;
    public nombre_aseguradora: string;
    public id_ramo: number;
    public id_producto: number;
    public id_plan: number;
    public id_asegurado_principal: number;
    public endosado: number;
    public nombre_endosado: string;
    public moneda: number;
    public total_prima: number;
    public fecha_inicio: Date;
    public fecha_fin_vigencia: Date;
    public debito_automatico: number;
    public fecha_vencimiento_comision: Date;
    public pct_comision: number;
    public dia_pago: number;
    public poliza: string;
    public certificado: string;
    public expediente: string;
    public pct_endoso: number;
    public id_vendedor: number;
    public vendedor: string;

    public impuesto: number;
    public gastos_emision: number;
    public nombre_debito: string;
    public numero_tarjeta: string;
    public vencimiento_tarjeta: Date;
    public banco_emisor: string;
    public tipo_tarjeta: number;
    public neta_prima: number;
    public inciso: string;
    public tipo: string;
    public id_grupo: number;
    public nombre_asegurado_principal: string;
    public nombre_producto: string;

    id_forma_pago: number;
    monto_cuota: number;
    ultimo_numero_cuota: number;
    monto_pagado_previo: number;
    fecha_proxima_cuota: Date;
    public alias: string;
    public alias_mostrar: string;
    public usuario_ingresa: string;
    public eliminado: number;
    public filtro: string;
    public flag: number;
    public tasaMillar: number;
    public pctISV: number;

    constructor() {
        this.ID = 0;
        this.id_cliente = 0;
        this.descripcion = '';
        this.nombre_cliente = '';
        this.id_aseguradora = 0;
        this.id_producto = 0;
        this.id_plan = 0;
        this.id_asegurado_principal = 0;
        this.endosado = 0;
        this.nombre_endosado = '';
        this.moneda = 0;
        this.total_prima = 0;
        this.fecha_inicio = new Date;
        this.fecha_fin_vigencia = new Date;
        this.debito_automatico = 0;
        this.fecha_vencimiento_comision = new Date;
        this.pct_comision = 0;
        this.dia_pago = 0;
        this.poliza = '';
        this.certificado = '';
        this.expediente = '';
        this.pct_endoso = 0;
        this.vendedor = '';
        this.impuesto = 0;
        this.gastos_emision = 0;
        this.nombre_debito = '';
        this.numero_tarjeta = '';
        this.vencimiento_tarjeta = new Date;
        this.banco_emisor = '';
        this.tipo_tarjeta = 0;
        this.neta_prima = 0;
        this.id_vendedor = 0;
        this.inciso = '';
        this.id_ramo = 0;
        this.nombre_aseguradora = '';
        this.tipo = '';
        this.id_grupo = 0;
        this.nombre_asegurado_principal = '';
        this.nombre_producto = '';

        this.id_forma_pago = 0;
        this.monto_cuota = 0;
        this.ultimo_numero_cuota = 0;
        this.monto_pagado_previo = 0;
        this.fecha_proxima_cuota = new Date();

        this.alias = '';
        this.alias_mostrar = '';
        this.usuario_ingresa = '';
        this.eliminado = 0;
        this.filtro = '';
        this.flag = 0;
        this.tasaMillar = 0;
        this.pctISV = 0;
    }
}
